# Generated by Django 4.2.21 on 2025-07-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
